### ISSUE TITLE
Help with calling external functions

### ISSUE THREAD

**Issue by GhostDog98** [onurkun/RustAegis#1]
Let's say I have the following function(s):
```rs
#[vm_protect(level="paranoid")]
fn is_license_valid() -> bool {
    // Placeholder for license validation logic
    // In a real application, implement actual license checking here
    true
}

#[vm_protect(level="paranoid")]
fn exit_conditions() -> bool {
    // If we are inside a vm...
    if inside_vm::inside_vm(){
        log::error!("VM detected! Exiting...");
        return true;
    }

    if !is_license_valid() {
        log::error!("Invalid license! Exiting...");
        return true;
    }

    return false;
}
```
While it appears the is_license_valid function compiles correctly, the exit_conditions does not. Instead, it says:
```
error: VM compilation error: Function calls not yet supported (use native calls)
  --> src\main.rs:25:1
   |
25 | / fn exit_conditions() -> bool {
26 | |     // If we are inside a vm...
27 | |     if inside_vm::inside_vm(){
28 | |         log::error!("VM detected! Exiting...");
...  |
37 | |     return false;
38 | | }
   | |_^
```

This somewhat obviously limits what I can do with it. As such, I have a few follow up questions:
- Is there any sort of work around for this?
- Does this limitation apply to all functions, or just those from external crates
- Is there anything I can do to help getting this feature implemented?

**Comment by GhostDog98** [comment]
Many thanks! 
You should probably add `spin` as a dependancy in your package since otherwise it appears to break itself. I also appear to be having a warning in my specific script and am unable to figure out why, that was introduced in this most recent version.
```
warning: unexpected `cfg` condition value: `std`
  --> src/main.rs:26:1
   |
26 | #[vm_protect(level = "paranoid")]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: no expected values for `feature`
   = note: using a cfg inside a attribute macro will use the cfgs from the destination crate and not the ones from the defining crate
   = help: try referring to `vm_protect` crate for guidance on how handle this unexpected cfg
   = help: the attribute macro `vm_protect` may come from an old version of the `aegis_vm_macro` crate, try updating your dependency with `cargo update -p aegis_vm_macro`
   = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
   = note: `#[warn(unexpected_cfgs)]` on by default
   = note: this warning originates in the attribute macro `vm_protect` (in Nightly builds, run with -Z macro-backtrace for more info)
```

With my code now being:
```rs
use inside_vm::{inside_vm};
use aegis_vm::vm_protect;


fn is_license_valid() -> bool {
    // Placeholder for license validation logic
    // In a real application, implement actual license checking here
    true
}

#[vm_protect]
fn exit_conditions() -> bool {
    // If we are inside a vm...

    let inside_vm_bool: bool = inside_vm();
    if inside_vm_bool {
        return true;
    }

    let license_key: bool = is_license_valid();

    if license_key == false {
        return true;
    }

    return false;
}
```
I'm assuming you may have missed another deps or feature flag?

**Comment by onurkun** [comment]
Thanks for the detailed report! You're absolutely right - this was our bug.

  The proc-macro generates spin::Once code for no_std builds, but we forgot to add spin as a dependency in aegis_vm. This has been fixed in v0.2.4.

  Fix: Added spin = { version = "0.9", default-features = false, features = ["once"] } to dependencies.

  Please update to v0.2.4 and let me know if you encounter any other issues!
  
  Can you try and share results with me?

**Comment by GhostDog98** [comment]
I'm still getting:
```rs
warning: unexpected `cfg` condition value: `std`
   --> src/main.rs:25:1
    |
 25 | #[vm_protect("paranoid")]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^ in this attribute macro expansion
    |
   ::: /home/ghostdog/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aegis_vm_macro-0.2.2/src/lib.rs:148:1
    |
148 | pub fn vm_protect(attr: TokenStream, item: TokenStream) -> TokenStream {
    | ---------------------------------------------------------------------- in this expansion of `#[vm_protect]`
    |
    = note: no expected values for `feature`
    = note: using a cfg inside a attribute macro will use the cfgs from the destination crate and not the ones from the defining crate
    = help: try referring to `vm_protect` crate for guidance on how handle this unexpected cfg
    = help: the attribute macro `vm_protect` may come from an old version of the `aegis_vm_macro` crate, try updating your dependency with `cargo update -p aegis_vm_macro`
    = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
    = note: `#[warn(unexpected_cfgs)]` on by default
```
<details><summary>All my packages (output of package tree)</summary>
<code>
├── aegis_vm v0.2.4
│   ├── aegis_vm_macro v0.2.2 (proc-macro)
│   │   ├── aes-gcm v0.10.3
│   │   │   ├── aead v0.5.2
│   │   │   │   ├── crypto-common v0.1.7
│   │   │   │   │   ├── generic-array v0.14.7
│   │   │   │   │   │   └── typenum v1.19.0
│   │   │   │   │   │   [build-dependencies]
│   │   │   │   │   │   └── version_check v0.9.5
│   │   │   │   │   ├── rand_core v0.6.4
│   │   │   │   │   │   └── getrandom v0.2.16
│   │   │   │   │   │       ├── cfg-if v1.0.4
│   │   │   │   │   │       └── libc v0.2.178
│   │   │   │   │   └── typenum v1.19.0
│   │   │   │   └── generic-array v0.14.7 (*)
│   │   │   ├── aes v0.8.4
│   │   │   │   ├── cfg-if v1.0.4
│   │   │   │   ├── cipher v0.4.4
│   │   │   │   │   ├── crypto-common v0.1.7 (*)
│   │   │   │   │   └── inout v0.1.4
│   │   │   │   │       └── generic-array v0.14.7 (*)
│   │   │   │   └── cpufeatures v0.2.17
│   │   │   ├── cipher v0.4.4 (*)
│   │   │   ├── ctr v0.9.2
│   │   │   │   └── cipher v0.4.4 (*)
│   │   │   ├── ghash v0.5.1
│   │   │   │   ├── opaque-debug v0.3.1
│   │   │   │   └── polyval v0.6.2
│   │   │   │       ├── cfg-if v1.0.4
│   │   │   │       ├── cpufeatures v0.2.17
│   │   │   │       ├── opaque-debug v0.3.1
│   │   │   │       └── universal-hash v0.5.1
│   │   │   │           ├── crypto-common v0.1.7 (*)
│   │   │   │           └── subtle v2.6.1
│   │   │   └── subtle v2.6.1
│   │   ├── hex v0.4.3
│   │   ├── hmac v0.12.1
│   │   │   └── digest v0.10.7
│   │   │       ├── block-buffer v0.10.4
│   │   │       │   └── generic-array v0.14.7 (*)
│   │   │       ├── crypto-common v0.1.7 (*)
│   │   │       └── subtle v2.6.1
│   │   ├── proc-macro2 v1.0.103
│   │   │   └── unicode-ident v1.0.22
│   │   ├── quote v1.0.42
│   │   │   └── proc-macro2 v1.0.103 (*)
│   │   ├── sha2 v0.10.9
│   │   │   ├── cfg-if v1.0.4
│   │   │   ├── cpufeatures v0.2.17
│   │   │   └── digest v0.10.7 (*)
│   │   └── syn v2.0.111
│   │       ├── proc-macro2 v1.0.103 (*)
│   │       ├── quote v1.0.42 (*)
│   │       └── unicode-ident v1.0.22
│   ├── aes-gcm v0.10.3 (*)
│   ├── digest v0.10.7 (*)
│   ├── fastrand v2.3.0
│   ├── hmac v0.12.1 (*)
│   ├── sha2 v0.10.9 (*)
│   ├── spin v0.9.8
│   └── subtle v2.6.1
│   [build-dependencies]
│   ├── hex v0.4.3
│   ├── hmac v0.12.1 (*)
│   └── sha2 v0.10.9 (*)
├── arboard v3.6.1
│   ├── image v0.25.9
│   │   ├── bytemuck v1.24.0
│   │   │   └── bytemuck_derive v1.10.2 (proc-macro)
│   │   │       ├── proc-macro2 v1.0.103 (*)
│   │   │       ├── quote v1.0.42 (*)
│   │   │       └── syn v2.0.111 (*)
│   │   ├── byteorder-lite v0.1.0
│   │   ├── moxcms v0.7.11
│   │   │   ├── num-traits v0.2.19
│   │   │   │   [build-dependencies]
│   │   │   │   └── autocfg v1.5.0
│   │   │   └── pxfm v0.1.27
│   │   │       └── num-traits v0.2.19 (*)
│   │   ├── num-traits v0.2.19 (*)
│   │   └── png v0.18.0
│   │       ├── bitflags v2.10.0
│   │       ├── crc32fast v1.5.0
│   │       │   └── cfg-if v1.0.4
│   │       ├── fdeflate v0.3.7
│   │       │   └── simd-adler32 v0.3.8
│   │       ├── flate2 v1.1.5
│   │       │   ├── crc32fast v1.5.0 (*)
│   │       │   └── miniz_oxide v0.8.9
│   │       │       ├── adler2 v2.0.1
│   │       │       └── simd-adler32 v0.3.8
│   │       └── miniz_oxide v0.8.9 (*)
│   ├── log v0.4.29
│   ├── parking_lot v0.12.5
│   │   ├── lock_api v0.4.14
│   │   │   └── scopeguard v1.2.0
│   │   └── parking_lot_core v0.9.12
│   │       ├── cfg-if v1.0.4
│   │       ├── libc v0.2.178
│   │       └── smallvec v1.15.1
│   ├── percent-encoding v2.3.2
│   └── x11rb v0.13.2
│       ├── gethostname v1.1.0
│       │   └── rustix v1.1.2
│       │       ├── bitflags v2.10.0
│       │       └── linux-raw-sys v0.11.0
│       ├── rustix v1.1.2 (*)
│       └── x11rb-protocol v0.13.2
├── eframe v0.24.1
│   ├── egui v0.24.1
│   │   ├── accesskit v0.12.3
│   │   ├── ahash v0.8.12
│   │   │   ├── cfg-if v1.0.4
│   │   │   ├── once_cell v1.21.3
│   │   │   └── zerocopy v0.8.31
│   │   │   [build-dependencies]
│   │   │   └── version_check v0.9.5
│   │   ├── epaint v0.24.1
│   │   │   ├── ab_glyph v0.2.32
│   │   │   │   ├── ab_glyph_rasterizer v0.1.10
│   │   │   │   └── owned_ttf_parser v0.25.1
│   │   │   │       └── ttf-parser v0.25.1
│   │   │   ├── ahash v0.8.12 (*)
│   │   │   ├── bytemuck v1.24.0 (*)
│   │   │   ├── ecolor v0.24.1
│   │   │   │   └── bytemuck v1.24.0 (*)
│   │   │   ├── emath v0.24.1
│   │   │   │   └── bytemuck v1.24.0 (*)
│   │   │   ├── log v0.4.29
│   │   │   ├── nohash-hasher v0.2.0
│   │   │   └── parking_lot v0.12.5 (*)
│   │   ├── log v0.4.29
│   │   └── nohash-hasher v0.2.0
│   ├── egui-winit v0.24.1
│   │   ├── accesskit_winit v0.15.0
│   │   │   ├── accesskit v0.12.3
│   │   │   ├── accesskit_unix v0.6.2
│   │   │   │   ├── accesskit v0.12.3
│   │   │   │   ├── accesskit_consumer v0.16.1
│   │   │   │   │   └── accesskit v0.12.3
│   │   │   │   ├── async-channel v2.5.0
│   │   │   │   │   ├── concurrent-queue v2.5.0
│   │   │   │   │   │   └── crossbeam-utils v0.8.21
│   │   │   │   │   ├── event-listener-strategy v0.5.4
│   │   │   │   │   │   ├── event-listener v5.4.1
│   │   │   │   │   │   │   ├── concurrent-queue v2.5.0 (*)
│   │   │   │   │   │   │   ├── parking v2.2.1
│   │   │   │   │   │   │   └── pin-project-lite v0.2.16
│   │   │   │   │   │   └── pin-project-lite v0.2.16
│   │   │   │   │   ├── futures-core v0.3.31
│   │   │   │   │   └── pin-project-lite v0.2.16
│   │   │   │   ├── async-once-cell v0.5.4
│   │   │   │   ├── atspi v0.19.0
│   │   │   │   │   ├── atspi-common v0.3.0
│   │   │   │   │   │   ├── enumflags2 v0.7.12
│   │   │   │   │   │   │   ├── enumflags2_derive v0.7.12 (proc-macro)
│   │   │   │   │   │   │   │   ├── proc-macro2 v1.0.103 (*)
│   │   │   │   │   │   │   │   ├── quote v1.0.42 (*)
│   │   │   │   │   │   │   │   └── syn v2.0.111 (*)
│   │   │   │   │   │   │   └── serde v1.0.228
│   │   │   │   │   │   │       ├── serde_core v1.0.228
│   │   │   │   │   │   │       └── serde_derive v1.0.228 (proc-macro)
│   │   │   │   │   │   │           ├── proc-macro2 v1.0.103 (*)
│   │   │   │   │   │   │           ├── quote v1.0.42 (*)
│   │   │   │   │   │   │           └── syn v2.0.111 (*)
│   │   │   │   │   │   ├── serde v1.0.228 (*)
│   │   │   │   │   │   ├── static_assertions v1.1.0
│   │   │   │   │   │   ├── zbus v3.15.2
│   │   │   │   │   │   │   ├── async-broadcast v0.5.1
│   │   │   │   │   │   │   │   ├── event-listener v2.5.3
│   │   │   │   │   │   │   │   └── futures-core v0.3.31
│   │   │   │   │   │   │   ├── async-executor v1.13.3
│   │   │   │   │   │   │   │   ├── async-task v4.7.1
│   │   │   │   │   │   │   │   ├── concurrent-queue v2.5.0 (*)
│   │   │   │   │   │   │   │   ├── fastrand v2.3.0
│   │   │   │   │   │   │   │   ├── futures-lite v2.6.1
│   │   │   │   │   │   │   │   │   ├── futures-core v0.3.31
│   │   │   │   │   │   │   │   │   └── pin-project-lite v0.2.16
│   │   │   │   │   │   │   │   ├── pin-project-lite v0.2.16
│   │   │   │   │   │   │   │   └── slab v0.4.11
│   │   │   │   │   │   │   ├── async-fs v1.6.0
│   │   │   │   │   │   │   │   ├── async-lock v2.8.0
│   │   │   │   │   │   │   │   │   └── event-listener v2.5.3
│   │   │   │   │   │   │   │   ├── blocking v1.6.2
│   │   │   │   │   │   │   │   │   ├── async-channel v2.5.0 (*)
│   │   │   │   │   │   │   │   │   ├── async-task v4.7.1
│   │   │   │   │   │   │   │   │   ├── futures-io v0.3.31
│   │   │   │   │   │   │   │   │   ├── futures-lite v2.6.1 (*)
│   │   │   │   │   │   │   │   │   └── piper v0.2.4
│   │   │   │   │   │   │   │   │       ├── atomic-waker v1.1.2
│   │   │   │   │   │   │   │   │       ├── fastrand v2.3.0
│   │   │   │   │   │   │   │   │       └── futures-io v0.3.31
│   │   │   │   │   │   │   │   └── futures-lite v1.13.0
│   │   │   │   │   │   │   │       ├── fastrand v1.9.0
│   │   │   │   │   │   │   │       ├── futures-core v0.3.31
│   │   │   │   │   │   │   │       ├── futures-io v0.3.31
│   │   │   │   │   │   │   │       ├── memchr v2.7.6
│   │   │   │   │   │   │   │       ├── parking v2.2.1
│   │   │   │   │   │   │   │       ├── pin-project-lite v0.2.16
│   │   │   │   │   │   │   │       └── waker-fn v1.2.0
│   │   │   │   │   │   │   │   [build-dependencies]
│   │   │   │   │   │   │   │   └── autocfg v1.5.0
│   │   │   │   │   │   │   ├── async-io v1.13.0
│   │   │   │   │   │   │   │   ├── async-lock v2.8.0 (*)
│   │   │   │   │   │   │   │   ├── cfg-if v1.0.4
│   │   │   │   │   │   │   │   ├── concurrent-queue v2.5.0 (*)
│   │   │   │   │   │   │   │   ├── futures-lite v1.13.0 (*)
│   │   │   │   │   │   │   │   ├── log v0.4.29
│   │   │   │   │   │   │   │   ├── parking v2.2.1
│   │   │   │   │   │   │   │   ├── polling v2.8.0
│   │   │   │   │   │   │   │   │   ├── cfg-if v1.0.4
│   │   │   │   │   │   │   │   │   ├── libc v0.2.178
│   │   │   │   │   │   │   │   │   └── log v0.4.29
│   │   │   │   │   │   │   │   │   [build-dependencies]
│   │   │   │   │   │   │   │   │   └── autocfg v1.5.0
│   │   │   │   │   │   │   │   ├── rustix v0.37.28
│   │   │   │   │   │   │   │   │   ├── bitflags v1.3.2
│   │   │   │   │   │   │   │   │   ├── io-lifetimes v1.0.11
│   │   │   │   │   │   │   │   │   │   └── libc v0.2.178
│   │   │   │   │   │   │   │   │   └── linux-raw-sys v0.3.8
│   │   │   │   │   │   │   │   ├── slab v0.4.11
│   │   │   │   │   │   │   │   ├── socket2 v0.4.10
│   │   │   │   │   │   │   │   │   └── libc v0.2.178
│   │   │   │   │   │   │   │   └── waker-fn v1.2.0
│   │   │   │   │   │   │   │   [build-dependencies]
│   │   │   │   │   │   │   │   └── autocfg v1.5.0
│   │   │   │   │   │   │   ├── async-lock v2.8.0 (*)
│   │   │   │   │   │   │   ├── async-recursion v1.1.1 (proc-macro)
│   │   │   │   │   │   │   │   ├── proc-macro2 v1.0.103 (*)
│   │   │   │   │   │   │   │   ├── quote v1.0.42 (*)
│   │   │   │   │   │   │   │   └── syn v2.0.111 (*)
│   │   │   │   │   │   │   ├── async-task v4.7.1
│   │   │   │   │   │   │   ├── async-trait v0.1.89 (proc-macro)
│   │   │   │   │   │   │   │   ├── proc-macro2 v1.0.103 (*)
│   │   │   │   │   │   │   │   ├── quote v1.0.42 (*)
│   │   │   │   │   │   │   │   └── syn v2.0.111 (*)
│   │   │   │   │   │   │   ├── blocking v1.6.2 (*)
│   │   │   │   │   │   │   ├── byteorder v1.5.0
│   │   │   │   │   │   │   ├── derivative v2.2.0 (proc-macro)
│   │   │   │   │   │   │   │   ├── proc-macro2 v1.0.103 (*)
│   │   │   │   │   │   │   │   ├── quote v1.0.42 (*)
│   │   │   │   │   │   │   │   └── syn v1.0.109
│   │   │   │   │   │   │   │       ├── proc-macro2 v1.0.103 (*)
│   │   │   │   │   │   │   │       ├── quote v1.0.42 (*)
│   │   │   │   │   │   │   │       └── unicode-ident v1.0.22
│   │   │   │   │   │   │   ├── enumflags2 v0.7.12 (*)
│   │   │   │   │   │   │   ├── event-listener v2.5.3
│   │   │   │   │   │   │   ├── futures-core v0.3.31
│   │   │   │   │   │   │   ├── futures-sink v0.3.31
│   │   │   │   │   │   │   ├── futures-util v0.3.31
│   │   │   │   │   │   │   │   ├── futures-channel v0.3.31
│   │   │   │   │   │   │   │   │   ├── futures-core v0.3.31
│   │   │   │   │   │   │   │   │   └── futures-sink v0.3.31
│   │   │   │   │   │   │   │   ├── futures-core v0.3.31
│   │   │   │   │   │   │   │   ├── futures-io v0.3.31
│   │   │   │   │   │   │   │   ├── futures-macro v0.3.31 (proc-macro)
│   │   │   │   │   │   │   │   │   ├── proc-macro2 v1.0.103 (*)
│   │   │   │   │   │   │   │   │   ├── quote v1.0.42 (*)
│   │   │   │   │   │   │   │   │   └── syn v2.0.111 (*)
│   │   │   │   │   │   │   │   ├── futures-sink v0.3.31
│   │   │   │   │   │   │   │   ├── futures-task v0.3.31
│   │   │   │   │   │   │   │   ├── memchr v2.7.6
│   │   │   │   │   │   │   │   ├── pin-project-lite v0.2.16
│   │   │   │   │   │   │   │   ├── pin-utils v0.1.0
│   │   │   │   │   │   │   │   └── slab v0.4.11
│   │   │   │   │   │   │   ├── hex v0.4.3
│   │   │   │   │   │   │   ├── nix v0.26.4
│   │   │   │   │   │   │   │   ├── bitflags v1.3.2
│   │   │   │   │   │   │   │   ├── cfg-if v1.0.4
│   │   │   │   │   │   │   │   ├── libc v0.2.178
│   │   │   │   │   │   │   │   └── memoffset v0.7.1
│   │   │   │   │   │   │   │       [build-dependencies]
│   │   │   │   │   │   │   │       └── autocfg v1.5.0
│   │   │   │   │   │   │   ├── once_cell v1.21.3
│   │   │   │   │   │   │   ├── ordered-stream v0.2.0
│   │   │   │   │   │   │   │   ├── futures-core v0.3.31
│   │   │   │   │   │   │   │   └── pin-project-lite v0.2.16
│   │   │   │   │   │   │   ├── rand v0.8.5
│   │   │   │   │   │   │   │   ├── libc v0.2.178
│   │   │   │   │   │   │   │   ├── rand_chacha v0.3.1
│   │   │   │   │   │   │   │   │   ├── ppv-lite86 v0.2.21
│   │   │   │   │   │   │   │   │   │   └── zerocopy v0.8.31
│   │   │   │   │   │   │   │   │   └── rand_core v0.6.4
│   │   │   │   │   │   │   │   │       └── getrandom v0.2.16
│   │   │   │   │   │   │   │   │           ├── cfg-if v1.0.4
│   │   │   │   │   │   │   │   │           └── libc v0.2.178
│   │   │   │   │   │   │   │   └── rand_core v0.6.4 (*)
│   │   │   │   │   │   │   ├── serde v1.0.228 (*)
│   │   │   │   │   │   │   ├── serde_repr v0.1.20 (proc-macro)
│   │   │   │   │   │   │   │   ├── proc-macro2 v1.0.103 (*)
│   │   │   │   │   │   │   │   ├── quote v1.0.42 (*)
│   │   │   │   │   │   │   │   └── syn v2.0.111 (*)
│   │   │   │   │   │   │   ├── sha1 v0.10.6
│   │   │   │   │   │   │   │   ├── cfg-if v1.0.4
│   │   │   │   │   │   │   │   ├── cpufeatures v0.2.17
│   │   │   │   │   │   │   │   └── digest v0.10.7 (*)
│   │   │   │   │   │   │   ├── static_assertions v1.1.0
│   │   │   │   │   │   │   ├── tracing v0.1.43
│   │   │   │   │   │   │   │   ├── pin-project-lite v0.2.16
│   │   │   │   │   │   │   │   ├── tracing-attributes v0.1.31 (proc-macro)
│   │   │   │   │   │   │   │   │   ├── proc-macro2 v1.0.103 (*)
│   │   │   │   │   │   │   │   │   ├── quote v1.0.42 (*)
│   │   │   │   │   │   │   │   │   └── syn v2.0.111 (*)
│   │   │   │   │   │   │   │   └── tracing-core v0.1.35
│   │   │   │   │   │   │   │       └── once_cell v1.21.3
│   │   │   │   │   │   │   ├── xdg-home v1.3.0
│   │   │   │   │   │   │   │   └── libc v0.2.178
│   │   │   │   │   │   │   ├── zbus_macros v3.15.2 (proc-macro)
│   │   │   │   │   │   │   │   ├── proc-macro-crate v1.3.1
│   │   │   │   │   │   │   │   │   ├── once_cell v1.21.3
│   │   │   │   │   │   │   │   │   └── toml_edit v0.19.15
│   │   │   │   │   │   │   │   │       ├── indexmap v2.12.1
│   │   │   │   │   │   │   │   │       │   ├── equivalent v1.0.2
│   │   │   │   │   │   │   │   │       │   └── hashbrown v0.16.1
│   │   │   │   │   │   │   │   │       ├── toml_datetime v0.6.11
│   │   │   │   │   │   │   │   │       └── winnow v0.5.40
│   │   │   │   │   │   │   │   ├── proc-macro2 v1.0.103 (*)
│   │   │   │   │   │   │   │   ├── quote v1.0.42 (*)
│   │   │   │   │   │   │   │   ├── regex v1.12.2
│   │   │   │   │   │   │   │   │   ├── aho-corasick v1.1.4
│   │   │   │   │   │   │   │   │   │   └── memchr v2.7.6
│   │   │   │   │   │   │   │   │   ├── memchr v2.7.6
│   │   │   │   │   │   │   │   │   ├── regex-automata v0.4.13
│   │   │   │   │   │   │   │   │   │   ├── aho-corasick v1.1.4 (*)
│   │   │   │   │   │   │   │   │   │   ├── memchr v2.7.6
│   │   │   │   │   │   │   │   │   │   └── regex-syntax v0.8.8
│   │   │   │   │   │   │   │   │   └── regex-syntax v0.8.8
│   │   │   │   │   │   │   │   ├── syn v1.0.109 (*)
│   │   │   │   │   │   │   │   └── zvariant_utils v1.0.1
│   │   │   │   │   │   │   │       ├── proc-macro2 v1.0.103 (*)
│   │   │   │   │   │   │   │       ├── quote v1.0.42 (*)
│   │   │   │   │   │   │   │       └── syn v1.0.109 (*)
│   │   │   │   │   │   │   ├── zbus_names v2.6.1
│   │   │   │   │   │   │   │   ├── serde v1.0.228 (*)
│   │   │   │   │   │   │   │   ├── static_assertions v1.1.0
│   │   │   │   │   │   │   │   └── zvariant v3.15.2
│   │   │   │   │   │   │   │       ├── byteorder v1.5.0
│   │   │   │   │   │   │   │       ├── enumflags2 v0.7.12 (*)
│   │   │   │   │   │   │   │       ├── libc v0.2.178
│   │   │   │   │   │   │   │       ├── serde v1.0.228 (*)
│   │   │   │   │   │   │   │       ├── static_assertions v1.1.0
│   │   │   │   │   │   │   │       └── zvariant_derive v3.15.2 (proc-macro)
│   │   │   │   │   │   │   │           ├── proc-macro-crate v1.3.1 (*)
│   │   │   │   │   │   │   │           ├── proc-macro2 v1.0.103 (*)
│   │   │   │   │   │   │   │           ├── quote v1.0.42 (*)
│   │   │   │   │   │   │   │           ├── syn v1.0.109 (*)
│   │   │   │   │   │   │   │           └── zvariant_utils v1.0.1 (*)
│   │   │   │   │   │   │   └── zvariant v3.15.2 (*)
│   │   │   │   │   │   ├── zbus_names v2.6.1 (*)
│   │   │   │   │   │   └── zvariant v3.15.2 (*)
│   │   │   │   │   ├── atspi-connection v0.3.0
│   │   │   │   │   │   ├── atspi-common v0.3.0 (*)
│   │   │   │   │   │   ├── atspi-proxies v0.3.0
│   │   │   │   │   │   │   ├── atspi-common v0.3.0 (*)
│   │   │   │   │   │   │   ├── serde v1.0.228 (*)
│   │   │   │   │   │   │   └── zbus v3.15.2 (*)
│   │   │   │   │   │   ├── futures-lite v1.13.0 (*)
│   │   │   │   │   │   └── zbus v3.15.2 (*)
│   │   │   │   │   └── atspi-proxies v0.3.0 (*)
│   │   │   │   ├── futures-lite v1.13.0 (*)
│   │   │   │   ├── once_cell v1.21.3
│   │   │   │   ├── serde v1.0.228 (*)
│   │   │   │   └── zbus v3.15.2 (*)
│   │   │   └── winit v0.28.7
│   │   │       ├── bitflags v1.3.2
│   │   │       ├── instant v0.1.13
│   │   │       │   └── cfg-if v1.0.4
│   │   │       ├── libc v0.2.178
│   │   │       ├── log v0.4.29
│   │   │       ├── mio v0.8.11
│   │   │       │   ├── libc v0.2.178
│   │   │       │   └── log v0.4.29
│   │   │       ├── once_cell v1.21.3
│   │   │       ├── percent-encoding v2.3.2
│   │   │       ├── raw-window-handle v0.5.2
│   │   │       ├── sctk-adwaita v0.5.4
│   │   │       │   ├── ab_glyph v0.2.32 (*)
│   │   │       │   ├── log v0.4.29
│   │   │       │   ├── memmap2 v0.5.10
│   │   │       │   │   └── libc v0.2.178
│   │   │       │   ├── smithay-client-toolkit v0.16.1
│   │   │       │   │   ├── bitflags v1.3.2
│   │   │       │   │   ├── calloop v0.10.6
│   │   │       │   │   │   ├── bitflags v1.3.2
│   │   │       │   │   │   ├── log v0.4.29
│   │   │       │   │   │   ├── nix v0.25.1
│   │   │       │   │   │   │   ├── bitflags v1.3.2
│   │   │       │   │   │   │   ├── cfg-if v1.0.4
│   │   │       │   │   │   │   ├── libc v0.2.178
│   │   │       │   │   │   │   └── memoffset v0.6.5
│   │   │       │   │   │   │       [build-dependencies]
│   │   │       │   │   │   │       └── autocfg v1.5.0
│   │   │       │   │   │   │   [build-dependencies]
│   │   │       │   │   │   │   └── autocfg v1.5.0
│   │   │       │   │   │   ├── slotmap v1.1.1
│   │   │       │   │   │   │   [build-dependencies]
│   │   │       │   │   │   │   └── version_check v0.9.5
│   │   │       │   │   │   ├── thiserror v1.0.69
│   │   │       │   │   │   │   └── thiserror-impl v1.0.69 (proc-macro)
│   │   │       │   │   │   │       ├── proc-macro2 v1.0.103 (*)
│   │   │       │   │   │   │       ├── quote v1.0.42 (*)
│   │   │       │   │   │   │       └── syn v2.0.111 (*)
│   │   │       │   │   │   └── vec_map v0.8.2
│   │   │       │   │   ├── dlib v0.5.2
│   │   │       │   │   │   └── libloading v0.8.9
│   │   │       │   │   │       └── cfg-if v1.0.4
│   │   │       │   │   ├── lazy_static v1.5.0
│   │   │       │   │   ├── log v0.4.29
│   │   │       │   │   ├── memmap2 v0.5.10 (*)
│   │   │       │   │   ├── nix v0.24.3
│   │   │       │   │   │   ├── bitflags v1.3.2
│   │   │       │   │   │   ├── cfg-if v1.0.4
│   │   │       │   │   │   ├── libc v0.2.178
│   │   │       │   │   │   └── memoffset v0.6.5 (*)
│   │   │       │   │   ├── wayland-client v0.29.5
│   │   │       │   │   │   ├── bitflags v1.3.2
│   │   │       │   │   │   ├── downcast-rs v1.2.1
│   │   │       │   │   │   ├── libc v0.2.178
│   │   │       │   │   │   ├── nix v0.24.3 (*)
│   │   │       │   │   │   ├── scoped-tls v1.0.1
│   │   │       │   │   │   ├── wayland-commons v0.29.5
│   │   │       │   │   │   │   ├── nix v0.24.3 (*)
│   │   │       │   │   │   │   ├── once_cell v1.21.3
│   │   │       │   │   │   │   ├── smallvec v1.15.1
│   │   │       │   │   │   │   └── wayland-sys v0.29.5
│   │   │       │   │   │   │       ├── dlib v0.5.2 (*)
│   │   │       │   │   │   │       └── lazy_static v1.5.0
│   │   │       │   │   │   │       [build-dependencies]
│   │   │       │   │   │   │       └── pkg-config v0.3.32
│   │   │       │   │   │   └── wayland-sys v0.29.5 (*)
│   │   │       │   │   │   [build-dependencies]
│   │   │       │   │   │   └── wayland-scanner v0.29.5
│   │   │       │   │   │       ├── proc-macro2 v1.0.103 (*)
│   │   │       │   │   │       ├── quote v1.0.42 (*)
│   │   │       │   │   │       └── xml-rs v0.8.28
│   │   │       │   │   ├── wayland-cursor v0.29.5
│   │   │       │   │   │   ├── nix v0.24.3 (*)
│   │   │       │   │   │   ├── wayland-client v0.29.5 (*)
│   │   │       │   │   │   └── xcursor v0.3.10
│   │   │       │   │   └── wayland-protocols v0.29.5
│   │   │       │   │       ├── bitflags v1.3.2
│   │   │       │   │       ├── wayland-client v0.29.5 (*)
│   │   │       │   │       └── wayland-commons v0.29.5 (*)
│   │   │       │   │       [build-dependencies]
│   │   │       │   │       └── wayland-scanner v0.29.5 (*)
│   │   │       │   │   [build-dependencies]
│   │   │       │   │   └── pkg-config v0.3.32
│   │   │       │   └── tiny-skia v0.8.4
│   │   │       │       ├── arrayref v0.3.9
│   │   │       │       ├── arrayvec v0.7.6
│   │   │       │       ├── bytemuck v1.24.0 (*)
│   │   │       │       ├── cfg-if v1.0.4
│   │   │       │       ├── png v0.17.16
│   │   │       │       │   ├── bitflags v1.3.2
│   │   │       │       │   ├── crc32fast v1.5.0 (*)
│   │   │       │       │   ├── fdeflate v0.3.7 (*)
│   │   │       │       │   ├── flate2 v1.1.5 (*)
│   │   │       │       │   └── miniz_oxide v0.8.9 (*)
│   │   │       │       └── tiny-skia-path v0.8.4
│   │   │       │           ├── arrayref v0.3.9
│   │   │       │           ├── bytemuck v1.24.0 (*)
│   │   │       │           └── strict-num v0.1.1
│   │   │       ├── smithay-client-toolkit v0.16.1 (*)
│   │   │       ├── wayland-client v0.29.5 (*)
│   │   │       ├── wayland-commons v0.29.5 (*)
│   │   │       ├── wayland-protocols v0.29.5 (*)
│   │   │       └── x11-dl v2.21.0
│   │   │           ├── libc v0.2.178
│   │   │           └── once_cell v1.21.3
│   │   │           [build-dependencies]
│   │   │           └── pkg-config v0.3.32
│   │   │       [build-dependencies]
│   │   │       ├── cfg_aliases v0.1.1
│   │   │       └── wayland-scanner v0.29.5 (*)
│   │   ├── arboard v3.6.1 (*)
│   │   ├── egui v0.24.1 (*)
│   │   ├── log v0.4.29
│   │   ├── raw-window-handle v0.5.2
│   │   ├── smithay-clipboard v0.6.6
│   │   │   ├── smithay-client-toolkit v0.16.1 (*)
│   │   │   └── wayland-client v0.29.5 (*)
│   │   ├── web-time v0.2.4
│   │   ├── webbrowser v0.8.15
│   │   │   ├── home v0.5.12
│   │   │   ├── log v0.4.29
│   │   │   └── url v2.5.7
│   │   │       ├── form_urlencoded v1.2.2
│   │   │       │   └── percent-encoding v2.3.2
│   │   │       ├── idna v1.1.0
│   │   │       │   ├── idna_adapter v1.2.1
│   │   │       │   │   ├── icu_normalizer v2.1.1
│   │   │       │   │   │   ├── icu_collections v2.1.1
│   │   │       │   │   │   │   ├── displaydoc v0.2.5 (proc-macro)
│   │   │       │   │   │   │   │   ├── proc-macro2 v1.0.103 (*)
│   │   │       │   │   │   │   │   ├── quote v1.0.42 (*)
│   │   │       │   │   │   │   │   └── syn v2.0.111 (*)
│   │   │       │   │   │   │   ├── potential_utf v0.1.4
│   │   │       │   │   │   │   │   └── zerovec v0.11.5
│   │   │       │   │   │   │   │       ├── yoke v0.8.1
│   │   │       │   │   │   │   │       │   ├── stable_deref_trait v1.2.1
│   │   │       │   │   │   │   │       │   ├── yoke-derive v0.8.1 (proc-macro)
│   │   │       │   │   │   │   │       │   │   ├── proc-macro2 v1.0.103 (*)
│   │   │       │   │   │   │   │       │   │   ├── quote v1.0.42 (*)
│   │   │       │   │   │   │   │       │   │   ├── syn v2.0.111 (*)
│   │   │       │   │   │   │   │       │   │   └── synstructure v0.13.2
│   │   │       │   │   │   │   │       │   │       ├── proc-macro2 v1.0.103 (*)
│   │   │       │   │   │   │   │       │   │       ├── quote v1.0.42 (*)
│   │   │       │   │   │   │   │       │   │       └── syn v2.0.111 (*)
│   │   │       │   │   │   │   │       │   └── zerofrom v0.1.6
│   │   │       │   │   │   │   │       │       └── zerofrom-derive v0.1.6 (proc-macro)
│   │   │       │   │   │   │   │       │           ├── proc-macro2 v1.0.103 (*)
│   │   │       │   │   │   │   │       │           ├── quote v1.0.42 (*)
│   │   │       │   │   │   │   │       │           ├── syn v2.0.111 (*)
│   │   │       │   │   │   │   │       │           └── synstructure v0.13.2 (*)
│   │   │       │   │   │   │   │       ├── zerofrom v0.1.6 (*)
│   │   │       │   │   │   │   │       └── zerovec-derive v0.11.2 (proc-macro)
│   │   │       │   │   │   │   │           ├── proc-macro2 v1.0.103 (*)
│   │   │       │   │   │   │   │           ├── quote v1.0.42 (*)
│   │   │       │   │   │   │   │           └── syn v2.0.111 (*)
│   │   │       │   │   │   │   ├── yoke v0.8.1 (*)
│   │   │       │   │   │   │   ├── zerofrom v0.1.6 (*)
│   │   │       │   │   │   │   └── zerovec v0.11.5 (*)
│   │   │       │   │   │   ├── icu_normalizer_data v2.1.1
│   │   │       │   │   │   ├── icu_provider v2.1.1
│   │   │       │   │   │   │   ├── displaydoc v0.2.5 (proc-macro) (*)
│   │   │       │   │   │   │   ├── icu_locale_core v2.1.1
│   │   │       │   │   │   │   │   ├── displaydoc v0.2.5 (proc-macro) (*)
│   │   │       │   │   │   │   │   ├── litemap v0.8.1
│   │   │       │   │   │   │   │   ├── tinystr v0.8.2
│   │   │       │   │   │   │   │   │   ├── displaydoc v0.2.5 (proc-macro) (*)
│   │   │       │   │   │   │   │   │   └── zerovec v0.11.5 (*)
│   │   │       │   │   │   │   │   ├── writeable v0.6.2
│   │   │       │   │   │   │   │   └── zerovec v0.11.5 (*)
│   │   │       │   │   │   │   ├── writeable v0.6.2
│   │   │       │   │   │   │   ├── yoke v0.8.1 (*)
│   │   │       │   │   │   │   ├── zerofrom v0.1.6 (*)
│   │   │       │   │   │   │   ├── zerotrie v0.2.3
│   │   │       │   │   │   │   │   ├── displaydoc v0.2.5 (proc-macro) (*)
│   │   │       │   │   │   │   │   ├── yoke v0.8.1 (*)
│   │   │       │   │   │   │   │   └── zerofrom v0.1.6 (*)
│   │   │       │   │   │   │   └── zerovec v0.11.5 (*)
│   │   │       │   │   │   ├── smallvec v1.15.1
│   │   │       │   │   │   └── zerovec v0.11.5 (*)
│   │   │       │   │   └── icu_properties v2.1.2
│   │   │       │   │       ├── icu_collections v2.1.1 (*)
│   │   │       │   │       ├── icu_locale_core v2.1.1 (*)
│   │   │       │   │       ├── icu_properties_data v2.1.2
│   │   │       │   │       ├── icu_provider v2.1.1 (*)
│   │   │       │   │       ├── zerotrie v0.2.3 (*)
│   │   │       │   │       └── zerovec v0.11.5 (*)
│   │   │       │   ├── smallvec v1.15.1
│   │   │       │   └── utf8_iter v1.0.4
│   │   │       ├── percent-encoding v2.3.2
│   │   │       └── serde v1.0.228 (*)
│   │   └── winit v0.28.7 (*)
│   ├── egui_glow v0.24.1
│   │   ├── bytemuck v1.24.0 (*)
│   │   ├── egui v0.24.1 (*)
│   │   ├── glow v0.12.3
│   │   ├── log v0.4.29
│   │   └── memoffset v0.7.1 (*)
│   ├── glow v0.12.3
│   ├── glutin v0.30.10
│   │   ├── bitflags v1.3.2
│   │   ├── glutin_egl_sys v0.5.1
│   │   │   [build-dependencies]
│   │   │   └── gl_generator v0.14.0
│   │   │       ├── khronos_api v3.1.0
│   │   │       ├── log v0.4.29
│   │   │       └── xml-rs v0.8.28
│   │   ├── glutin_glx_sys v0.4.0
│   │   │   └── x11-dl v2.21.0 (*)
│   │   │   [build-dependencies]
│   │   │   └── gl_generator v0.14.0 (*)
│   │   ├── libloading v0.7.4
│   │   │   └── cfg-if v1.0.4
│   │   ├── once_cell v1.21.3
│   │   ├── raw-window-handle v0.5.2
│   │   ├── wayland-sys v0.30.1
│   │   │   ├── dlib v0.5.2 (*)
│   │   │   ├── lazy_static v1.5.0
│   │   │   └── log v0.4.29
│   │   │   [build-dependencies]
│   │   │   └── pkg-config v0.3.32
│   │   └── x11-dl v2.21.0 (*)
│   │   [build-dependencies]
│   │   └── cfg_aliases v0.1.1
│   ├── glutin-winit v0.3.0
│   │   ├── glutin v0.30.10 (*)
│   │   ├── raw-window-handle v0.5.2
│   │   └── winit v0.28.7 (*)
│   │   [build-dependencies]
│   │   └── cfg_aliases v0.1.1
│   ├── image v0.24.9
│   │   ├── bytemuck v1.24.0 (*)
│   │   ├── byteorder v1.5.0
│   │   ├── color_quant v1.1.0
│   │   ├── num-traits v0.2.19 (*)
│   │   └── png v0.17.16 (*)
│   ├── log v0.4.29
│   ├── parking_lot v0.12.5 (*)
│   ├── raw-window-handle v0.5.2
│   ├── static_assertions v1.1.0
│   ├── thiserror v1.0.69 (*)
│   └── winit v0.28.7 (*)
├── enigo v0.5.0
│   ├── libc v0.2.178
│   ├── log v0.4.29
│   ├── nom v8.0.0
│   │   └── memchr v2.7.6
│   ├── x11rb v0.13.2 (*)
│   ├── xkbcommon v0.8.0
│   │   ├── libc v0.2.178
│   │   ├── memmap2 v0.9.9
│   │   │   └── libc v0.2.178
│   │   └── xkeysym v0.2.1
│   └── xkeysym v0.2.1
├── env_logger v0.10.2
│   ├── humantime v2.3.0
│   ├── is-terminal v0.4.17
│   │   └── libc v0.2.178
│   ├── log v0.4.29
│   ├── regex v1.12.2 (*)
│   └── termcolor v1.4.1
├── fastrand v2.3.0
├── inside-vm v0.2.0
├── keygen-rs v0.8.1
│   ├── aes-gcm v0.10.3 (*)
│   ├── async-trait v0.1.89 (proc-macro) (*)
│   ├── base64 v0.21.7
│   ├── chrono v0.4.42
│   │   ├── iana-time-zone v0.1.64
│   │   ├── num-traits v0.2.19 (*)
│   │   └── serde v1.0.228 (*)
│   ├── dotenv v0.15.0
│   ├── ed25519-dalek v2.2.0
│   │   ├── curve25519-dalek v4.1.3
│   │   │   ├── cfg-if v1.0.4
│   │   │   ├── cpufeatures v0.2.17
│   │   │   ├── curve25519-dalek-derive v0.1.1 (proc-macro)
│   │   │   │   ├── proc-macro2 v1.0.103 (*)
│   │   │   │   ├── quote v1.0.42 (*)
│   │   │   │   └── syn v2.0.111 (*)
│   │   │   ├── digest v0.10.7 (*)
│   │   │   ├── subtle v2.6.1
│   │   │   └── zeroize v1.8.2
│   │   │   [build-dependencies]
│   │   │   └── rustc_version v0.4.1
│   │   │       └── semver v1.0.27
│   │   ├── ed25519 v2.2.3
│   │   │   └── signature v2.2.0
│   │   ├── rand_core v0.6.4 (*)
│   │   ├── sha2 v0.10.9 (*)
│   │   ├── subtle v2.6.1
│   │   └── zeroize v1.8.2
│   ├── futures v0.3.31
│   │   ├── futures-channel v0.3.31 (*)
│   │   ├── futures-core v0.3.31
│   │   ├── futures-executor v0.3.31
│   │   │   ├── futures-core v0.3.31
│   │   │   ├── futures-task v0.3.31
│   │   │   └── futures-util v0.3.31 (*)
│   │   ├── futures-io v0.3.31
│   │   ├── futures-sink v0.3.31
│   │   ├── futures-task v0.3.31
│   │   └── futures-util v0.3.31 (*)
│   ├── futures-timer v3.0.3
│   ├── hex v0.4.3
│   ├── hostname v0.4.2
│   │   ├── cfg-if v1.0.4
│   │   └── libc v0.2.178
│   ├── lazy_static v1.5.0
│   ├── log v0.4.29
│   ├── mockito v0.31.1
│   │   ├── assert-json-diff v2.0.2
│   │   │   ├── serde v1.0.228 (*)
│   │   │   └── serde_json v1.0.145
│   │   │       ├── itoa v1.0.15
│   │   │       ├── memchr v2.7.6
│   │   │       ├── ryu v1.0.20
│   │   │       └── serde_core v1.0.228
│   │   ├── colored v2.2.0
│   │   │   └── lazy_static v1.5.0
│   │   ├── httparse v1.10.1
│   │   ├── lazy_static v1.5.0
│   │   ├── log v0.4.29
│   │   ├── rand v0.8.5 (*)
│   │   ├── regex v1.12.2 (*)
│   │   ├── serde_json v1.0.145 (*)
│   │   ├── serde_urlencoded v0.7.1
│   │   │   ├── form_urlencoded v1.2.2 (*)
│   │   │   ├── itoa v1.0.15
│   │   │   ├── ryu v1.0.20
│   │   │   └── serde v1.0.228 (*)
│   │   └── similar v2.7.0
│   ├── num_cpus v1.17.0
│   │   └── libc v0.2.178
│   ├── rand v0.8.5 (*)
│   ├── reqwest v0.11.27
│   │   ├── base64 v0.21.7
│   │   ├── bytes v1.11.0
│   │   ├── encoding_rs v0.8.35
│   │   │   └── cfg-if v1.0.4
│   │   ├── futures-core v0.3.31
│   │   ├── futures-util v0.3.31 (*)
│   │   ├── h2 v0.3.27
│   │   │   ├── bytes v1.11.0
│   │   │   ├── fnv v1.0.7
│   │   │   ├── futures-core v0.3.31
│   │   │   ├── futures-sink v0.3.31
│   │   │   ├── futures-util v0.3.31 (*)
│   │   │   ├── http v0.2.12
│   │   │   │   ├── bytes v1.11.0
│   │   │   │   ├── fnv v1.0.7
│   │   │   │   └── itoa v1.0.15
│   │   │   ├── indexmap v2.12.1 (*)
│   │   │   ├── slab v0.4.11
│   │   │   ├── tokio v1.48.0
│   │   │   │   ├── bytes v1.11.0
│   │   │   │   ├── libc v0.2.178
│   │   │   │   ├── mio v1.1.1
│   │   │   │   │   └── libc v0.2.178
│   │   │   │   ├── parking_lot v0.12.5 (*)
│   │   │   │   ├── pin-project-lite v0.2.16
│   │   │   │   ├── signal-hook-registry v1.4.7
│   │   │   │   │   └── libc v0.2.178
│   │   │   │   ├── socket2 v0.6.1
│   │   │   │   │   └── libc v0.2.178
│   │   │   │   └── tokio-macros v2.6.0 (proc-macro)
│   │   │   │       ├── proc-macro2 v1.0.103 (*)
│   │   │   │       ├── quote v1.0.42 (*)
│   │   │   │       └── syn v2.0.111 (*)
│   │   │   ├── tokio-util v0.7.17
│   │   │   │   ├── bytes v1.11.0
│   │   │   │   ├── futures-core v0.3.31
│   │   │   │   ├── futures-sink v0.3.31
│   │   │   │   ├── pin-project-lite v0.2.16
│   │   │   │   └── tokio v1.48.0 (*)
│   │   │   └── tracing v0.1.43 (*)
│   │   ├── http v0.2.12 (*)
│   │   ├── http-body v0.4.6
│   │   │   ├── bytes v1.11.0
│   │   │   ├── http v0.2.12 (*)
│   │   │   └── pin-project-lite v0.2.16
│   │   ├── hyper v0.14.32
│   │   │   ├── bytes v1.11.0
│   │   │   ├── futures-channel v0.3.31 (*)
│   │   │   ├── futures-core v0.3.31
│   │   │   ├── futures-util v0.3.31 (*)
│   │   │   ├── h2 v0.3.27 (*)
│   │   │   ├── http v0.2.12 (*)
│   │   │   ├── http-body v0.4.6 (*)
│   │   │   ├── httparse v1.10.1
│   │   │   ├── httpdate v1.0.3
│   │   │   ├── itoa v1.0.15
│   │   │   ├── pin-project-lite v0.2.16
│   │   │   ├── socket2 v0.5.10
│   │   │   │   └── libc v0.2.178
│   │   │   ├── tokio v1.48.0 (*)
│   │   │   ├── tower-service v0.3.3
│   │   │   ├── tracing v0.1.43 (*)
│   │   │   └── want v0.3.1
│   │   │       └── try-lock v0.2.5
│   │   ├── hyper-rustls v0.24.2
│   │   │   ├── futures-util v0.3.31 (*)
│   │   │   ├── http v0.2.12 (*)
│   │   │   ├── hyper v0.14.32 (*)
│   │   │   ├── rustls v0.21.12
│   │   │   │   ├── log v0.4.29
│   │   │   │   ├── ring v0.17.14
│   │   │   │   │   ├── cfg-if v1.0.4
│   │   │   │   │   ├── getrandom v0.2.16 (*)
│   │   │   │   │   └── untrusted v0.9.0
│   │   │   │   │   [build-dependencies]
│   │   │   │   │   └── cc v1.2.49
│   │   │   │   │       ├── find-msvc-tools v0.1.5
│   │   │   │   │       └── shlex v1.3.0
│   │   │   │   ├── rustls-webpki v0.101.7
│   │   │   │   │   ├── ring v0.17.14 (*)
│   │   │   │   │   └── untrusted v0.9.0
│   │   │   │   └── sct v0.7.1
│   │   │   │       ├── ring v0.17.14 (*)
│   │   │   │       └── untrusted v0.9.0
│   │   │   ├── tokio v1.48.0 (*)
│   │   │   └── tokio-rustls v0.24.1
│   │   │       ├── rustls v0.21.12 (*)
│   │   │       └── tokio v1.48.0 (*)
│   │   ├── ipnet v2.11.0
│   │   ├── log v0.4.29
│   │   ├── mime v0.3.17
│   │   ├── once_cell v1.21.3
│   │   ├── percent-encoding v2.3.2
│   │   ├── pin-project-lite v0.2.16
│   │   ├── rustls v0.21.12 (*)
│   │   ├── rustls-pemfile v1.0.4
│   │   │   └── base64 v0.21.7
│   │   ├── serde v1.0.228 (*)
│   │   ├── serde_json v1.0.145 (*)
│   │   ├── serde_urlencoded v0.7.1 (*)
│   │   ├── sync_wrapper v0.1.2
│   │   ├── tokio v1.48.0 (*)
│   │   ├── tokio-rustls v0.24.1 (*)
│   │   ├── tower-service v0.3.3
│   │   ├── url v2.5.7 (*)
│   │   └── webpki-roots v0.25.4
│   ├── serde v1.0.228 (*)
│   ├── serde_json v1.0.145 (*)
│   ├── serde_urlencoded v0.7.1 (*)
│   ├── sha2 v0.10.9 (*)
│   ├── subtle v2.6.1
│   ├── thiserror v1.0.69 (*)
│   ├── tokio v1.48.0 (*)
│   └── url v2.5.7 (*)
├── log v0.4.29
├── raw-window-handle v0.5.2
├── spin v0.9.8
└── winapi v0.3.9
</code>
</details>

**Comment by onurkun** [comment]
Hi! Thanks for your patience - I found and fixed multiple issues:

  v0.2.51 fixes:

  1. Missing spin dependency - Added spin = "0.10"
  2. cfg warning - The macro was generating #[cfg(feature = "std")] which checks the user's crate features, not aegis_vm's. Removed entirely.
  3. no_std compatibility - The generated code used Vec and spin::Once directly, which aren't available in user's #![no_std] crates. Now uses re-exports from 
  aegis_vm:
    - aegis_vm::SpinOnce 
    - aegis_vm::StdVec

  We tested with a #![no_std] crate and confirmed it compiles without errors or warnings.

  Please update to v0.2.51 - Can you send me results?
